// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	data "codeberg.org/ehrktia/lendbook/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// GetID is an autogenerated mock type for the GetID type
type GetID struct {
	mock.Mock
}

type GetID_Expecter struct {
	mock *mock.Mock
}

func (_m *GetID) EXPECT() *GetID_Expecter {
	return &GetID_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function with given fields: ctx, id
func (_m *GetID) GetById(ctx context.Context, id string) (data.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 data.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (data.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) data.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetID_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type GetID_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *GetID_Expecter) GetById(ctx interface{}, id interface{}) *GetID_GetById_Call {
	return &GetID_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *GetID_GetById_Call) Run(run func(ctx context.Context, id string)) *GetID_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GetID_GetById_Call) Return(_a0 data.User, _a1 error) *GetID_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GetID_GetById_Call) RunAndReturn(run func(context.Context, string) (data.User, error)) *GetID_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// NewGetID creates a new instance of GetID. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetID(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetID {
	mock := &GetID{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
