// Code generated by mockery v2.52.3. DO NOT EDIT.

package mocks

import (
	context "context"

	data "codeberg.org/ehrktia/lendbook/internal/data"
	mock "github.com/stretchr/testify/mock"
)

// UserQuery is an autogenerated mock type for the UserQuery type
type UserQuery struct {
	mock.Mock
}

type UserQuery_Expecter struct {
	mock *mock.Mock
}

func (_m *UserQuery) EXPECT() *UserQuery_Expecter {
	return &UserQuery_Expecter{mock: &_m.Mock}
}

// GetBookByUserId provides a mock function with given fields: ctx, ownerId
func (_m *UserQuery) GetBookByUserId(ctx context.Context, ownerId float64) ([]data.Book, error) {
	ret := _m.Called(ctx, ownerId)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByUserId")
	}

	var r0 []data.Book
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, float64) ([]data.Book, error)); ok {
		return rf(ctx, ownerId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, float64) []data.Book); ok {
		r0 = rf(ctx, ownerId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.Book)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, float64) error); ok {
		r1 = rf(ctx, ownerId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserQuery_GetBookByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByUserId'
type UserQuery_GetBookByUserId_Call struct {
	*mock.Call
}

// GetBookByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerId float64
func (_e *UserQuery_Expecter) GetBookByUserId(ctx interface{}, ownerId interface{}) *UserQuery_GetBookByUserId_Call {
	return &UserQuery_GetBookByUserId_Call{Call: _e.mock.On("GetBookByUserId", ctx, ownerId)}
}

func (_c *UserQuery_GetBookByUserId_Call) Run(run func(ctx context.Context, ownerId float64)) *UserQuery_GetBookByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(float64))
	})
	return _c
}

func (_c *UserQuery_GetBookByUserId_Call) Return(_a0 []data.Book, _a1 error) *UserQuery_GetBookByUserId_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserQuery_GetBookByUserId_Call) RunAndReturn(run func(context.Context, float64) ([]data.Book, error)) *UserQuery_GetBookByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function with given fields: ctx, id
func (_m *UserQuery) GetById(ctx context.Context, id string) (data.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 data.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (data.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) data.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(data.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserQuery_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type UserQuery_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UserQuery_Expecter) GetById(ctx interface{}, id interface{}) *UserQuery_GetById_Call {
	return &UserQuery_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *UserQuery_GetById_Call) Run(run func(ctx context.Context, id string)) *UserQuery_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserQuery_GetById_Call) Return(_a0 data.User, _a1 error) *UserQuery_GetById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserQuery_GetById_Call) RunAndReturn(run func(context.Context, string) (data.User, error)) *UserQuery_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserQuery) GetUserByEmail(ctx context.Context, email string) (string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserQuery_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type UserQuery_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *UserQuery_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *UserQuery_GetUserByEmail_Call {
	return &UserQuery_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *UserQuery_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *UserQuery_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UserQuery_GetUserByEmail_Call) Return(_a0 string, _a1 error) *UserQuery_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserQuery_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (string, error)) *UserQuery_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: ctx
func (_m *UserQuery) GetUsers(ctx context.Context) ([]data.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []data.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]data.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []data.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]data.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserQuery_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type UserQuery_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UserQuery_Expecter) GetUsers(ctx interface{}) *UserQuery_GetUsers_Call {
	return &UserQuery_GetUsers_Call{Call: _e.mock.On("GetUsers", ctx)}
}

func (_c *UserQuery_GetUsers_Call) Run(run func(ctx context.Context)) *UserQuery_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UserQuery_GetUsers_Call) Return(_a0 []data.User, _a1 error) *UserQuery_GetUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserQuery_GetUsers_Call) RunAndReturn(run func(context.Context) ([]data.User, error)) *UserQuery_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserQuery creates a new instance of UserQuery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserQuery(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserQuery {
	mock := &UserQuery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
