-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.books
(
    id bigserial NOT NULL,
    title character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    edition character varying(50),
    owner_id bigint NOT NULL,
    available boolean,
    added timestamp without time zone DEFAULT now(),
    updated timestamp without time zone,
    CONSTRAINT pk_book_id PRIMARY KEY (id)
);

COMMENT ON TABLE public.books
    IS 'holds books data';

CREATE TABLE IF NOT EXISTS public.lender
(
    first_name character varying(255) NOT NULL,
    last_name character varying(255) NOT NULL,
    id bigserial NOT NULL,
    email character varying(255) NOT NULL,
    active boolean,
    version int NOT NULL,
    CONSTRAINT pk_lender_id PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.book_lender
(
    book_id bigint NOT NULL,
    owner_id bigint NOT NULL,
    book_owner_id bigserial NOT NULL,
    CONSTRAINT pk_book_owner_id PRIMARY KEY (book_owner_id)
);

COMMENT ON TABLE public.book_lender
    IS 'holds book and owner relationship details';

ALTER TABLE IF EXISTS public.book_lender
    ADD CONSTRAINT fk_book_id FOREIGN KEY (book_id)
    REFERENCES public.books (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.book_lender
    ADD CONSTRAINT fk_owner_id FOREIGN KEY (owner_id)
    REFERENCES public.lender (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
